.\" knocker man page
.\" Process this file with: groff -man -Tascii
.\" man page originally written by  Gabriele Giorgetti <g.gabriele@europe.com>
.TH KNOCKER 1 "JULY 8, 2001"
.SH NAME
knocker \- A easy to use network security port scanner
.SH SYNOPSIS
.B \fBknocker\fR --host <host>
[\fIOPTION\fR]
.SH DESCRIPTION
.B knocker 
is a simple and easy to use TCP (no UDP yet) security port scanner
which is able to analyze hosts and all of the different services started on
them.
.SH OPTIONS
.TP
\fB\-H\fr, \fB\-\-host\fR
host name or numeric Internet address to scan
.TP
\fB\-SP\fr, \fB\-\-start-port\fR
port number to begin the scan from 
.TP
\fB\-EP\fr, \fB\-\-end-port\fR
port number to end the scan at 
.TP
\fB\-h\fR, \fB\-\-help\fR
display this help and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
output version information and exit
.SH EXAMPLES
.LP
To run this program the standard way type:
.LP
knocker --host 192.168.0.1
.LP
If you want to specify a port range to scan:
.LP
knocker --host 192.168.0.1  --start-port 1 --end-port 2600
.SH AVAILABILTY   
The latest version of this program can be found at
http://knocker.sourceforge.net
.SH BUGS
See the BUGS file in the knocker source package for a list of known bugs.
Report bugs to <g.gabriele@europe.com>
.SH AUTHOR
knocker is written by Gabriele Giorgetti <g.gabriele@europe.com>
.PP
This manual page is written by Gabriele Giorgetti 
<g.gabriele@europe.com>.
.SH COPYRIGHT
Copyright \(co 2001 Gabriele Giorgetti
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.